-- SELECCIONAR LA BASE DE DATOS
USE mysql;
-- USUARIO NORMAL
CREATE USER 'usuario_intranet'@'%' IDENTIFIED BY '1234567890';
GRANT SELECT,UPDATE,INSERT ON IntranetBatoi.* TO 'usuario_intranet'@'%';
-- USUARIO ADMINISTRADOR CON ACCESSO A TODO / MISMO ROL QUE ROOT
-- PARA LOCALHOST
FLUSH PRIVILEGES;
CREATE USER 'admin_intranet'@'localhost' IDENTIFIED BY '1234567890' ;
GRANT ALL PRIVILEGES ON IntranetBatoi.* TO 'admin_intranet'@'localhost' WITH GRANT OPTION;
-- GRANT RELOAD,PROCESS ON IntranetBatoi.* TO 'admin_intranet'@'localhost';
FLUSH PRIVILEGES;
-- USUARIO ADMINISTRADOR CON ACCESO ROOT
-- PARA LA RED EN LA QUE SE ENCUENTRA
CREATE USER 'admin_intranet'@'%' IDENTIFIED BY '1234567890';
GRANT ALL PRIVILEGES ON IntranetBatoi.* TO 'admin_intranet'@'%' WITH GRANT OPTION;
-- GRANT RELOAD,PROCESS ON IntranetBatoi.* TO 'admin_intranet'@'%';
FLUSH PRIVILEGES;