USE IntranetBatoi;
INSERT INTO `departamentos` (`CLITERAL`, `VLITERAL`, `DepCurt`) VALUES
('DESCONOCIDO','DESCONEGUT','Des'),
('INGLES', 'ANGLES', 'Ang'),
('DEPARTAMENTO ADMINISTRATIVO', 'DEPARTAMENT ADMINISTRACIÓ', 'Adm'),
('DEPARTAMENTO SANITARIO', 'DEPARTAMENT SANITARI', 'San'),
('EXTENSION CULTURAL', 'EXTENSIO CULTURAL', 'Cul'),
('FORMACION Y ORIENTACION LABORA', 'FORMACIO I ORIENTACIO LABORAL', 'Fol'),
('FRANCES', 'FRANCES', 'Fra'),
('ORIENTACION', 'ORIENTACIO', 'Ori'),
('CICLOS FORMATIVOS', 'CICLES FORMATIUS', 'Cf'),
('FCT', 'FCT', 'Fct'),
('DEPARTAMENTO INFORMATICA', 'DEPARTAMENT INFORMÀTICA', 'Inf'),
('SERVICIOS A LA COMUNIDAD', 'SEVEIS A LA COMUNITAT', 'SCo'),
('IMAGEN PERSONAL', 'IMATGE PERSONAL', 'Img'),
('PROGRAMAS DE GARANTIA SOCIAL', 'PROGRAMES DE GARANTIA SOCIAL', 'Pgs'),
('HOSTELERIA Y TURISMO', 'HOSTELERIA I TURISME', 'Hos');
