Use IntranetBatoi;
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFBA','2nFPB PERRUQUERIA I ESTETICA','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSP','1R CFS DIREC. CUINA','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSW','2N CFS DAW','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFBB','2nFPB INFORMATICA OFICINA','D',1234,3);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSQ','1R CFS TASOC LOGSE','D',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMR','2N CFM SERV.RESTAURA','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMQ','2N CFM CUINA -MATI-','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSS','2N CFS ASIX','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMS','1R CFM CUINA -V-','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFST','2N CFS LAB.DIAGN.CLINIC','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMU','2N CUINA -VESPRADA-','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSO','1R CFS ESTET.INTEGRA','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMA','1R CFM CAE MATI','D',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMB','1R CFM CAE VESPRADA','D',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSB','1R CFS ADM. I FINANC','D',1234,3);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSB','2N CFS ADM.I FINANC','D',1234,3);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMB','2N CFM GESTIO ADMINI','D',1234,3);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSF','1R CFS IMATGE DIAG-V','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSE','2N CFS SALUT AMBIENTAL','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSF','2N CFS IMAT. DIAG. V','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSC','1R CFS ASIX','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMC','1R GESTIÓ ADMINISTR.','D',1234,3);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMC','FCT CFM CAE -V-','D',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMA','FCT CFM CAE -M-','D',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMF','1R CFM ESTÈTICA','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMI','FCT CFM ESTETICA','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMG','1R CFM PERRUQUERIA','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMH','1R CFM SMX -A','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSG','1R CFS DAM','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMJ','2N CFM PERRUQ.COSMET.','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMI','1R CFM SMX -B','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSL','2N CFS DAM','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMK','2N CFM SMX -A-','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFML','2N CFM SMX -B-','D',1234,11);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMJ','1R CFM APD -M-','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSE','1R CFS SALUT AMBIENTAL','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMM','2N CFM APD -M-','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFML','1R CFM APD -V-','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMN','2N CFM APD -V-','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSH','1R CFS IMATG DIAGN-M','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSM','2N CFS IMAT. DIAG. M','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSN','2N CFS ESTET.INTEGRAL','D',1234,13);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMN','1R CFM CUINA -M-','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMP','1R CFM SERV. RESTAUR','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSJ','1R CFS LAB.DIAG.CLIN','D',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSK','1R CFS EDUC.INFANT.M','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSL','1R CFS EDUC.INFANT.V','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSM','1R CFS ANIMAC. SOCIO','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSO','2N CFS EDUCAC.INF.-V','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSP','2N CFS EDUCAC.INF.-M','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSQ','FCT CFS ANIM.SOCIOCULTURAL','D',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFBC','2n FPB CUINA I RESTAURACIO','D',1234,15);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMR','1R CFM CAE SEMIPR.-B','S',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFSN','1R CFS IMAT.DIAG.SEMIPRESENCI','S',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMT','1R CFM APD SEMIPRESENCIAL','S',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFSU','2N CFS IMAT.DIAGN.SEMIPRESENC','S',1234,4);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMW','2N FCT CFM CAE SEMI-B-','S',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMV','2N FCT CFM CAE SEMI-A-','S',1234,1);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('2CFMT','2N CFM APD SEMIPRESENCIAL','S',1234,12);
INSERT INTO grupos(codigo,nombre,turno,tutor,familia) VALUES ('1CFMQ','1R CFM CAE SEMIPR. A','S',1234,1);
