INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('02', 'Albacete');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('03', 'Alicante/Alacant');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('04', 'Almería');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('01', 'Araba/Álava');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('33', 'Asturias');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('05', 'Ávila');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('06', 'Badajoz');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('07', 'Balears,Illes');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('08', 'Barcelona');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('48', 'Bizkaia');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('09', 'Burgos');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('10', 'Cáceres');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('11', 'Cádiz');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('39', 'Cantabria');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('12', 'Castellón/Castelló');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('13', 'Ciudad Real');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('14', 'Córdoba');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('15', 'Coruña, A');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('16', 'Cuenca');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('20', 'Gipuzkoa');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('17', 'Girona');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('18', 'Granada');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('19', 'Gualadajara');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('21', 'Huelva');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('22', 'Huesca');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('23', 'Jaén');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('24', 'León');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('25', 'Lleida');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('27', 'Lugo');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('28', 'Madrid');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('29', 'Malaga');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('30', 'Murcia');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('31', 'Navarra');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('32', 'Ourense');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('34', 'Palencia');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('35', 'Palmas, Las');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('36', 'Pontevedra');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('26', 'Rioja, La');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('37', 'Salamanca');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('38', 'Santa Cruz de Tenerife');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('40', 'Segovia');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('41', 'Sevilla');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('42', 'Soria');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('43', 'Tarragona');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('44', 'Teruel');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('45', 'Toledo');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('46', 'Valencia/València');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('47', 'Valladolid');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('49', 'Zamora');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('50', 'Zaragoza');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('51', 'Ceuta');
INSERT INTO `IntranetBatoi`.`provincias` (`id`, `nombre`) VALUES ('52', 'Melilla');